### PR TITLE
Added missing quotes to js src attrbute

### PR DESCRIPTION
**Pull request by agalazis**
I realised that quotes on script scr attribute are missing and by having alook at the [inital commit](https://github.com/timomeh/ejs-helper/blob/4a1aba7ff21af36040413d097aae978805e406a1/lib/ejs-helper.js)  I guess this was a bug that resisted over time since modern browsers mitigate it appropriately  and nobody realized xD. Anw here you are, fixed and tested.

### CODE REVIEW

**Comment by timomeh** [comment]
Whoops, big fuck-up. :D Thanks for noticing!

Since I didn't write any tests (because I have lazy ass syndrome) and I didn't use it quite a while, I completely trust you regarding this.

I'll merge it, bump the version number and release it.

**Comment by timomeh** [comment]
(To be fair, it doesn't take a lot of trust for two quotes 😛 )

**Comment by timomeh** [comment]
Merged into master and published as version 1.0.3

**Comment by agalazis** [comment]
No worries, if i find some time in the near future I will write some tests so that even little trust is not needed 
:stuck_out_tongue_winking_eye:

**Pull request merged**
